namespace WindowsApps.Toolkit.WinUI.UI.Converters
{    
    runtimeclass BoolNegationConverter : 
            Microsoft.UI.Xaml.DependencyObject,
            [default]Microsoft.UI.Xaml.Data.IValueConverter
    {
        BoolNegationConverter();
    }
}
