namespace WindowsApps.Toolkit.WinUI.UI.Converters
{
    [default_interface]
    runtimeclass ColorToDisplayNameConverter : Microsoft.UI.Xaml.DependencyObject,
        [default]Microsoft.UI.Xaml.Data.IValueConverter
    {
        ColorToDisplayNameConverter();
    }
}
