import "UI/Converters/EmptyStringToObjectConverter.idl";

namespace WindowsApps.Toolkit.WinUI.UI.Converters
{
    [default_interface]
    runtimeclass StringVisibilityConverter : EmptyStringToObjectConverter
    {
        StringVisibilityConverter();
    }
}
