namespace WindowsApps.Toolkit.WinUI.Extensions
{
    [default_interface]
    static runtimeclass StringExtensions
    {
        static String GetLocalized(String resourceKey);
        static String GetLocalized(String resourceKey, Windows.UI.UIContext uiContext);
    }
}
