namespace WindowsApps.Toolkit.WinUI.Extensions
{
    [default_interface]
    static runtimeclass StringExtensions
    {
        static String GetLocalized(String resourceKey);
        static String GetLocalized(String resourceKey, Windows.UI.UIContext uiContext);
        [default_overload]
        static String GetLocalized(String resourceKey, String resourcePath);

        static String GetViewLocalized(String resourceKey);
        static String GetViewLocalized(String resourceKey, Windows.UI.UIContext uiContext);
    }
}
